theme: jekyll-theme-cayman
title: Live Server | VSCode Extension
description: Launch a development Live Server to browser from VSCode with live preview and live reload.
repository: ritwickdey/vscode-live-server

gems:
  - jekyll-seo-tag

title: Live Server | VSCode Extension
description : Launch a Live development Server to browser from VSCode with live preview and live reload
author : Ritwick Dey
twitter:username: Dey_Ritwick
social:
  name: Live Server VSCode Extension
  links:
    - https://github.com/ritwickdey/vscode-live-server
    - https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer
lang: en_IN

## Uncomment below for local test
# github: [metadata]

